### ISSUE TITLE
Missing implementation

### ISSUE THREAD

**Issue by stijndcl** [rjuszczyk/ComposeVideoPlayer#3]
There seems to be no actual code in this repository, and the commit history only shows changes to the README & `build.gradle.kts` files.

The [`/videoplayer`](https://github.com/rjuszczyk/ComposeVideoPlayer/tree/main/videoplayer) directory (where I presume the source code should be) is completely empty. The component itself is missing.

**Comment by rjuszczyk** [comment]
thanks for pointing out, something weird has happen, let me check why it was not pushed

**Comment by radodado** [comment]
should be resolved now
